#pragma once
#undef TAPPING_TERM
#define TAPPING_TERM 200 // ms; extend if accidental mods
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

/* Pointing-device */
#define POINTING_DEVICE_CPI 1200
#define POINTING_DEVICE_SNIPING_CPI 400
#define POINTING_DEVICE_SCROLL_DIVIDER 8
#define NATURAL_SCROLL_ENABLE

// #define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_ENABLE